"""Media storage behind one interface, so Cloudinary or S3-compatible storage can
replace local files without touching the rest of the app (spec section 6)."""

import re
from abc import ABC, abstractmethod
from pathlib import Path

from app.core.config import get_settings

_SAFE_KEY = re.compile(r"^[a-z0-9][a-z0-9/_.-]*$")


class Storage(ABC):
    @abstractmethod
    def save(self, key: str, data: bytes, content_type: str) -> str:
        """Stores `data` under `key` and returns its public URL."""

    @abstractmethod
    def read(self, key: str) -> bytes: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def url(self, key: str) -> str: ...


def check_key(key: str) -> str:
    # Keys are generated by us, but a path must still never escape the media root.
    if not _SAFE_KEY.match(key) or ".." in key:
        raise ValueError(f"Unsafe storage key: {key!r}")
    return key


class LocalStorage(Storage):
    """Files under MEDIA_ROOT, served by the API at /media. Suitable for development
    and single-server deployments; the Docker volume is shared by API and workers."""

    def __init__(self, root: str, base_url: str) -> None:
        self.root = Path(root)
        self.base_url = base_url

    def save(self, key: str, data: bytes, content_type: str) -> str:
        path = self.root / check_key(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write then rename, so a reader never sees half a file.
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_bytes(data)
        temporary.replace(path)
        return self.url(key)

    def read(self, key: str) -> bytes:
        return (self.root / check_key(key)).read_bytes()

    def delete(self, key: str) -> None:
        (self.root / check_key(key)).unlink(missing_ok=True)

    def url(self, key: str) -> str:
        return f"{self.base_url}/{check_key(key)}"


def get_storage() -> Storage:
    settings = get_settings()
    return LocalStorage(settings.media_root, settings.media_url)
