"""create post metrics and analytics syncs

Revision ID: f1762a155baa
Revises: 58a168c446ce
Create Date: 2026-09-26 11:37:39.343702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f1762a155baa'
down_revision: str | None = '58a168c446ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_syncs',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='analytics_sync_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('posts_synced', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_analytics_syncs_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_syncs'))
    )
    op.create_index(op.f('ix_analytics_syncs_brand_id'), 'analytics_syncs', ['brand_id'], unique=False)
    op.create_table('post_metrics',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('missing_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_post_metrics_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_metrics_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_metrics'))
    )
    op.create_index(op.f('ix_post_metrics_brand_id'), 'post_metrics', ['brand_id'], unique=False)
    op.create_index('ix_post_metrics_post_id_synced_at', 'post_metrics', ['post_id', 'synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_metrics_post_id_synced_at', table_name='post_metrics')
    op.drop_index(op.f('ix_post_metrics_brand_id'), table_name='post_metrics')
    op.drop_table('post_metrics')
    op.drop_index(op.f('ix_analytics_syncs_brand_id'), table_name='analytics_syncs')
    op.drop_table('analytics_syncs')
    # ### end Alembic commands ###
