"""create research items and runs

Revision ID: 4e3b789e44e2
Revises: 532d3bb0672c
Create Date: 2026-09-24 14:17:42.401618
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4e3b789e44e2'
down_revision: str | None = '532d3bb0672c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_items',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('article', 'feed_summary', 'page', name='research_content_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_research_items_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_research_items_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_items')),
    sa.UniqueConstraint('brand_id', 'canonical_url', name=op.f('uq_research_items_brand_id_canonical_url'))
    )
    op.create_index(op.f('ix_research_items_brand_id'), 'research_items', ['brand_id'], unique=False)
    op.create_index('ix_research_items_brand_id_content_hash', 'research_items', ['brand_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_research_items_source_id'), 'research_items', ['source_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', name='run_trigger', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='run_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('items_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_duplicate', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_research_runs_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_research_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index(op.f('ix_research_runs_brand_id'), 'research_runs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_research_runs_source_id'), 'research_runs', ['source_id'], unique=False)
    op.add_column('sources', sa.Column('next_fetch_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sources_next_fetch_at'), 'sources', ['next_fetch_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_next_fetch_at'), table_name='sources')
    op.drop_column('sources', 'next_fetch_at')
    op.drop_index(op.f('ix_research_runs_source_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_brand_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_research_items_source_id'), table_name='research_items')
    op.drop_index('ix_research_items_brand_id_content_hash', table_name='research_items')
    op.drop_index(op.f('ix_research_items_brand_id'), table_name='research_items')
    op.drop_table('research_items')
    # ### end Alembic commands ###
