"""create brand content pillars

Revision ID: ff1462762402
Revises: 44545a576bc9
Create Date: 2026-09-24 14:01:09.032647
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ff1462762402'
down_revision: str | None = '44545a576bc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_content_pillars',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('pillar', sa.Enum('educational', 'opinion', 'story', 'how_to', 'case_study', 'comparison', 'industry_insight', 'faq', 'behind_the_scenes', 'promotion', 'community', name='content_pillar', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('weight BETWEEN 0 AND 100', name=op.f('ck_brand_content_pillars_weight_percent')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_content_pillars_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_content_pillars')),
    sa.UniqueConstraint('brand_id', 'pillar', name=op.f('uq_brand_content_pillars_brand_id_pillar'))
    )
    op.create_index(op.f('ix_brand_content_pillars_brand_id'), 'brand_content_pillars', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_content_pillars_brand_id'), table_name='brand_content_pillars')
    op.drop_table('brand_content_pillars')
    # ### end Alembic commands ###
