"""create engage settings and inbox items

Revision ID: 6ad93fe60740
Revises: 5b1c7e995157
Create Date: 2026-09-28 09:20:16.949838
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6ad93fe60740'
down_revision: str | None = '5b1c7e995157'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engage_settings',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('off', 'review', 'auto', name='engage_mode', native_enum=False, create_constraint=True, length=40), server_default='off', nullable=False),
    sa.Column('reply_to_comments', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reply_to_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('business_facts', sa.Text(), server_default='', nullable=False),
    sa.Column('max_replies_per_day', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_engage_settings_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engage_settings')),
    sa.UniqueConstraint('brand_id', name=op.f('uq_engage_settings_brand_id'))
    )
    op.create_table('inbox_items',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=20), server_default='facebook', nullable=False),
    sa.Column('kind', sa.Enum('comment', 'message', name='inbox_kind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('thread_external_id', sa.String(length=200), nullable=True),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('author_external_id', sa.String(length=200), nullable=True),
    sa.Column('author_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('review', 'sent', 'dismissed', 'skipped', 'failed', name='inbox_status', native_enum=False, create_constraint=True, length=40), server_default='review', nullable=False),
    sa.Column('draft_reply', sa.Text(), server_default='', nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sent_reply', sa.Text(), nullable=True),
    sa.Column('sent_reply_external_id', sa.String(length=200), nullable=True),
    sa.Column('sent_automatically', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_inbox_items_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_inbox_items_post_id_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_items')),
    sa.UniqueConstraint('brand_id', 'platform', 'external_id', name=op.f('uq_inbox_items_brand_id_platform_external_id'))
    )
    op.create_index(op.f('ix_inbox_items_brand_id'), 'inbox_items', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbox_items_brand_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_table('engage_settings')
    # ### end Alembic commands ###
