"""create social accounts and publish error

Revision ID: 591aea9dd19c
Revises: 36f4463a5da7
Create Date: 2026-09-24 16:43:01.276447
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '591aea9dd19c'
down_revision: str | None = '36f4463a5da7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('active', 'reconnect_required', name='social_account_status', native_enum=False, create_constraint=True, length=40), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_social_accounts_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_social_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('brand_id', 'platform', name=op.f('uq_social_accounts_brand_id_platform'))
    )
    op.create_index(op.f('ix_social_accounts_brand_id'), 'social_accounts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.add_column('posts', sa.Column('publish_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'publish_error')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_brand_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
