"""create content generations and posts

Revision ID: dce7e7151cbc
Revises: 5a8b7b636202
Create Date: 2026-09-24 15:45:33.707735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'dce7e7151cbc'
down_revision: str | None = '5a8b7b636202'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generations',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='generation_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('hook_options', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('master_draft', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_content_generations_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['content_opportunities.id'], name=op.f('fk_content_generations_opportunity_id_content_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_generations'))
    )
    op.create_index(op.f('ix_content_generations_brand_id'), 'content_generations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_generations_opportunity_id'), 'content_generations', ['opportunity_id'], unique=False)
    op.create_table('posts',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('generation_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.Enum('text_post', 'carousel', 'thread', 'image_post', 'short_video', 'article', name='post_content_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('source_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('quality_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('idea', 'draft', 'review', 'approved', 'scheduled', 'publishing', 'published', 'failed', 'archived', name='post_status', native_enum=False, create_constraint=True, length=40), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_post_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_posts_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], name=op.f('fk_posts_generation_id_content_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['content_opportunities.id'], name=op.f('fk_posts_opportunity_id_content_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_brand_id'), 'posts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_posts_generation_id'), 'posts', ['generation_id'], unique=False)
    op.create_index(op.f('ix_posts_opportunity_id'), 'posts', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_opportunity_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_generation_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_brand_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_content_generations_opportunity_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_brand_id'), table_name='content_generations')
    op.drop_table('content_generations')
    # ### end Alembic commands ###
