"""add editor versions revisions and scheduling

Revision ID: 36f4463a5da7
Revises: a712bacd3d79
Create Date: 2026-09-24 16:18:36.043301
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '36f4463a5da7'
down_revision: str | None = 'a712bacd3d79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_revisions',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('rewrite', 'shorten', 'expand', 'change_tone', 'new_hook', 'new_cta', 'custom', name='revision_action', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('instruction', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='revision_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('base_hash', sa.String(length=64), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_post_revisions_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_revisions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_revisions'))
    )
    op.create_index(op.f('ix_post_revisions_brand_id'), 'post_revisions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_post_revisions_post_id'), 'post_revisions', ['post_id'], unique=False)
    op.create_table('post_versions',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_versions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_versions'))
    )
    op.create_index(op.f('ix_post_versions_post_id'), 'post_versions', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('review_note', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.drop_column('posts', 'review_note')
    op.drop_column('posts', 'approved_at')
    op.drop_index(op.f('ix_post_versions_post_id'), table_name='post_versions')
    op.drop_table('post_versions')
    op.drop_index(op.f('ix_post_revisions_post_id'), table_name='post_revisions')
    op.drop_index(op.f('ix_post_revisions_brand_id'), table_name='post_revisions')
    op.drop_table('post_revisions')
    # ### end Alembic commands ###
