"""create ai runs

Revision ID: 194d5b7e1e4d
Revises: 4e3b789e44e2
Create Date: 2026-09-24 14:30:48.458620
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '194d5b7e1e4d'
down_revision: str | None = '4e3b789e44e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'invalid_output', name='ai_run_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_ai_runs_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_runs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_brand_id'), 'ai_runs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_created_at'), 'ai_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_runs_task_type'), 'ai_runs', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_runs_user_id'), 'ai_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_runs_user_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_task_type'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_created_at'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_brand_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    # ### end Alembic commands ###
