"""create sources

Revision ID: 532d3bb0672c
Revises: ff1462762402
Create Date: 2026-09-24 14:07:58.017004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '532d3bb0672c'
down_revision: str | None = 'ff1462762402'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.Enum('website', 'blog', 'rss', 'youtube', 'reddit', 'news', 'search', 'user_url', 'api', name='source_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fetch_frequency', sa.Enum('hourly', 'every_6_hours', 'daily', 'weekly', name='fetch_frequency', native_enum=False, create_constraint=True, length=40), server_default='daily', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ok', 'error', name='source_status', native_enum=False, create_constraint=True, length=40), server_default='pending', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_sources_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('brand_id', 'url', name=op.f('uq_sources_brand_id_url'))
    )
    op.create_index(op.f('ix_sources_brand_id'), 'sources', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_brand_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
