"""create autopilot settings and runs

Revision ID: a621728cf8cb
Revises: f1762a155baa
Create Date: 2026-09-26 12:15:34.452720
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a621728cf8cb'
down_revision: str | None = 'f1762a155baa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autopilot_runs',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='autopilot_run_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('slots_open', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('research_queued', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('opportunities_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_scheduled', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_for_review', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_rejected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_autopilot_runs_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autopilot_runs'))
    )
    op.create_index(op.f('ix_autopilot_runs_brand_id'), 'autopilot_runs', ['brand_id'], unique=False)
    op.create_table('autopilot_settings',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('off', 'copilot', 'autopilot', name='autopilot_mode', native_enum=False, create_constraint=True, length=40), server_default='off', nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('post_time', sa.String(length=5), server_default='09:00', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('horizon_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('max_posts_per_run', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('auto_visual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approval_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_autopilot_settings_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autopilot_settings')),
    sa.UniqueConstraint('brand_id', name=op.f('uq_autopilot_settings_brand_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autopilot_settings')
    op.drop_index(op.f('ix_autopilot_runs_brand_id'), table_name='autopilot_runs')
    op.drop_table('autopilot_runs')
    # ### end Alembic commands ###
