"""create visuals

Revision ID: a712bacd3d79
Revises: dce7e7151cbc
Create Date: 2026-09-24 16:03:10.327804
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a712bacd3d79'
down_revision: str | None = 'dce7e7151cbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visuals',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('visual_type', sa.Enum('quote_card', 'minimal_graphic', 'infographic', 'carousel', 'illustration', 'cartoon', 'photo', 'meme', 'product_showcase', name='visual_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='visual_status', native_enum=False, create_constraint=True, length=40), server_default='queued', nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('concept', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_url', sa.String(length=2048), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_visuals_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_visuals_post_id_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visuals'))
    )
    op.create_index(op.f('ix_visuals_brand_id'), 'visuals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_visuals_post_id'), 'visuals', ['post_id'], unique=False)
    op.create_foreign_key('fk_posts_visual_id_visuals', 'posts', 'visuals', ['visual_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_visual_id_visuals', 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_visuals_post_id'), table_name='visuals')
    op.drop_index(op.f('ix_visuals_brand_id'), table_name='visuals')
    op.drop_table('visuals')
    # ### end Alembic commands ###
